import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateInvoicePDF = (invoice: any) => {
  const doc = new jsPDF() as any;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241);
  doc.text('CONSTRUCT OS', 105, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('CONSTRUCTION ERP SYSTEM', 105, 27, { align: 'center' });

  doc.setDrawColor(226, 232, 240);
  doc.line(20, 32, 190, 32);

  const startY = 45;
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text(`INVOICE: ${invoice.invoice_number || '—'}`, 20, startY);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, 20, startY + 8);
  doc.text(`DUE DATE: ${invoice.due_date || 'N/A'}`, 20, startY + 14);
  doc.text(`STATUS: ${(invoice.status || 'draft').toUpperCase()}`, 20, startY + 20);

  doc.text('BILL TO:', 130, startY);
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(invoice.project?.client_name || invoice.projects?.client_name || 'Client', 130, startY + 8);
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Project: ' + (invoice.project?.name || invoice.projects?.name || '—'), 130, startY + 14);

  doc.autoTable({
    startY: startY + 32,
    head: [['Description', 'Amount']],
    body: [
      [`Invoice ${invoice.invoice_number}`, `$${Number(invoice.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
  });

  const finalY = doc.lastAutoTable.finalY + 12;
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.text('TOTAL DUE:', 130, finalY);
  doc.setTextColor(99, 102, 241);
  doc.text(`$${Number(invoice.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 188, finalY, { align: 'right' });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Construct OS — Construction ERP', 105, 285, { align: 'center' });

  doc.save(`invoice_${invoice.invoice_number || 'export'}.pdf`);
};
